/* This example requires Tailwind CSS v2.0+ */
import ActivityCard from "./ActivityCard";

const activities = [
  {
    ActivityId: 17901,
    FilterId: 0,
    ActivityTypeId: 22,
    ProgramId: 120,
    ProgramType: "Drop In Activities                      ",
    MinAge: 8.0,
    MaxAge: 99.0,
    MinAgeType: "Y",
    MaxAgeType: "Y",
    SubProgramType: "Swimming",
    Title: "Lane Swim &#8776",
    Description:
      "<span style='color:red;'><a href='http://www7.mississauga.ca/departments/rec/aquatics/docs/swim_admission_standards.pdf' target='_blank' style='color:red;'><strong>Note:</strong>Click here to view the swim admission standards to help you have a safe and positive swim experience.</a></span><br />  \r\nLane swim is a structured swim for continuous lap swimming. This swim is best for those whom are comfortable in deep water and can swim 25m. Pools are divided into double lanes to allow for a circular pattern while swimming. Lane division will be based on the pace of the swimmers.<p style='display:none;'>no-email-reminder</p>",
    Barcode: "906941",
    FacilityName: "Lap Pool",
    LocationId: 22,
    LocationName: "River Grove CC",
    LocationAddress: "5800 River Grove Mississauga ON L5M 4R9",
    NumberOfClasses: 7,
    StartDate: "2021-11-02T06:30:00",
    EndDate: "2021-12-14T07:15:00",
    FriendlyStartTime: "November 2, 2021, 6:30 AM",
    FriendlyStartTime_ForSorting: "November 2, 2021, 06:30",
    FriendlyStartDate: "6:30 AM",
    FriendlyEndDate: "7:15 AM",
    SeasonString: null,
    FriendlyLength: "45 minutes",
    FriendlyStartMonth: "November 2, 2021",
    FriendlyEndMonth: "December 14, 2021",
    FriendlyDaysOfWeek: "Tue",
    Amount: 4.0,
    NumRegistered: 0,
    MaxRegistrants: 29,
    BookmarkedDate: "0001-01-01T00:00:00",
    ExclusionDates: "",
    InclusionDates: "Nov 30,",
    Id: 1075766,
  },
  {
    ActivityId: 17901,
    FilterId: 0,
    ActivityTypeId: 22,
    ProgramId: 120,
    ProgramType: "Drop In Activities                      ",
    MinAge: 8.0,
    MaxAge: 99.0,
    MinAgeType: "Y",
    MaxAgeType: "Y",
    SubProgramType: "Swimming",
    Title: "Lane Swim &#8776",
    Description:
      "<span style='color:red;'><a href='http://www7.mississauga.ca/departments/rec/aquatics/docs/swim_admission_standards.pdf' target='_blank' style='color:red;'><strong>Note:</strong>Click here to view the swim admission standards to help you have a safe and positive swim experience.</a></span><br />  \r\nLane swim is a structured swim for continuous lap swimming. This swim is best for those whom are comfortable in deep water and can swim 25m. Pools are divided into double lanes to allow for a circular pattern while swimming. Lane division will be based on the pace of the swimmers.<p style='display:none;'>no-email-reminder</p>",
    Barcode: "906955",
    FacilityName: "Lap Pool",
    LocationId: 22,
    LocationName: "River Grove CC",
    LocationAddress: "5800 River Grove Mississauga ON L5M 4R9",
    NumberOfClasses: 7,
    StartDate: "2021-11-03T06:30:00",
    EndDate: "2021-12-15T07:15:00",
    FriendlyStartTime: "November 3, 2021, 6:30 AM",
    FriendlyStartTime_ForSorting: "November 3, 2021, 06:30",
    FriendlyStartDate: "6:30 AM",
    FriendlyEndDate: "7:15 AM",
    SeasonString: null,
    FriendlyLength: "45 minutes",
    FriendlyStartMonth: "November 3, 2021",
    FriendlyEndMonth: "December 15, 2021",
    FriendlyDaysOfWeek: "Wed",
    Amount: 4.0,
    NumRegistered: 0,
    MaxRegistrants: 29,
    BookmarkedDate: "0001-01-01T00:00:00",
    ExclusionDates: "",
    InclusionDates: "Dec 01,",
    Id: 1075780,
  },
  {
    ActivityId: 17901,
    FilterId: 0,
    ActivityTypeId: 22,
    ProgramId: 120,
    ProgramType: "Drop In Activities                      ",
    MinAge: 8.0,
    MaxAge: 99.0,
    MinAgeType: "Y",
    MaxAgeType: "Y",
    SubProgramType: "Swimming",
    Title: "Lane Swim &#8776",
    Description:
      "<span style='color:red;'><a href='http://www7.mississauga.ca/departments/rec/aquatics/docs/swim_admission_standards.pdf' target='_blank' style='color:red;'><strong>Note:</strong>Click here to view the swim admission standards to help you have a safe and positive swim experience.</a></span><br />  \r\nLane swim is a structured swim for continuous lap swimming. This swim is best for those whom are comfortable in deep water and can swim 25m. Pools are divided into double lanes to allow for a circular pattern while swimming. Lane division will be based on the pace of the swimmers.<p style='display:none;'>no-email-reminder</p>",
    Barcode: "906901",
    FacilityName: "Lap Pool",
    LocationId: 22,
    LocationName: "River Grove CC",
    LocationAddress: "5800 River Grove Mississauga ON L5M 4R9",
    NumberOfClasses: 8,
    StartDate: "2021-10-29T06:30:00",
    EndDate: "2021-12-17T07:15:00",
    FriendlyStartTime: "October 29, 2021, 6:30 AM",
    FriendlyStartTime_ForSorting: "October 29, 2021, 06:30",
    FriendlyStartDate: "6:30 AM",
    FriendlyEndDate: "7:15 AM",
    SeasonString: null,
    FriendlyLength: "45 minutes",
    FriendlyStartMonth: "October 29, 2021",
    FriendlyEndMonth: "December 17, 2021",
    FriendlyDaysOfWeek: "Fri",
    Amount: 4.0,
    NumRegistered: 0,
    MaxRegistrants: 29,
    BookmarkedDate: "0001-01-01T00:00:00",
    ExclusionDates: "",
    InclusionDates: "Dec 03,",
    Id: 1075726,
  },
  {
    ActivityId: 17901,
    FilterId: 0,
    ActivityTypeId: 22,
    ProgramId: 120,
    ProgramType: "Drop In Activities                      ",
    MinAge: 8.0,
    MaxAge: 99.0,
    MinAgeType: "Y",
    MaxAgeType: "Y",
    SubProgramType: "Swimming",
    Title: "Lane Swim &#8776",
    Description:
      "<span style='color:red;'><a href='http://www7.mississauga.ca/departments/rec/aquatics/docs/swim_admission_standards.pdf' target='_blank' style='color:red;'><strong>Note:</strong>Click here to view the swim admission standards to help you have a safe and positive swim experience.</a></span><br />  \r\nLane swim is a structured swim for continuous lap swimming. This swim is best for those whom are comfortable in deep water and can swim 25m. Pools are divided into double lanes to allow for a circular pattern while swimming. Lane division will be based on the pace of the swimmers.<p style='display:none;'>no-email-reminder</p>",
    Barcode: "906441",
    FacilityName: "Main Pool",
    LocationId: 347,
    LocationName: "Frank McKechnie CC and Library",
    LocationAddress: "310 Bristol Mississauga ON L4Z 3V5",
    NumberOfClasses: 28,
    StartDate: "2021-10-29T06:30:00",
    EndDate: "2021-12-31T07:15:00",
    FriendlyStartTime: "October 29, 2021, 6:30 AM",
    FriendlyStartTime_ForSorting: "October 29, 2021, 06:30",
    FriendlyStartDate: "6:30 AM",
    FriendlyEndDate: "7:15 AM",
    SeasonString: null,
    FriendlyLength: "45 minutes",
    FriendlyStartMonth: "October 29, 2021",
    FriendlyEndMonth: "December 31, 2021",
    FriendlyDaysOfWeek: "Mon, Wed, Fri",
    Amount: 4.0,
    NumRegistered: 0,
    MaxRegistrants: 29,
    BookmarkedDate: "0001-01-01T00:00:00",
    ExclusionDates: "",
    InclusionDates: "Nov 29,Dec 01,Dec 03,",
    Id: 1075265,
  },
  {
    ActivityId: 17901,
    FilterId: 0,
    ActivityTypeId: 22,
    ProgramId: 120,
    ProgramType: "Drop In Activities                      ",
    MinAge: 8.0,
    MaxAge: 99.0,
    MinAgeType: "Y",
    MaxAgeType: "Y",
    SubProgramType: "Swimming",
    Title: "Lane Swim &#8776",
    Description:
      "<span style='color:red;'><a href='http://www7.mississauga.ca/departments/rec/aquatics/docs/swim_admission_standards.pdf' target='_blank' style='color:red;'><strong>Note:</strong>Click here to view the swim admission standards to help you have a safe and positive swim experience.</a></span><br />  \r\nLane swim is a structured swim for continuous lap swimming. This swim is best for those whom are comfortable in deep water and can swim 25m. Pools are divided into double lanes to allow for a circular pattern while swimming. Lane division will be based on the pace of the swimmers.<p style='display:none;'>no-email-reminder</p>",
    Barcode: "906730",
    FacilityName: "Main Pool",
    LocationId: 5,
    LocationName: "Huron Park CC",
    LocationAddress: "830 Paisley Mississauga ON L5C 3P5",
    NumberOfClasses: 9,
    StartDate: "2021-11-01T06:30:00",
    EndDate: "2021-12-27T07:15:00",
    FriendlyStartTime: "November 1, 2021, 6:30 AM",
    FriendlyStartTime_ForSorting: "November 1, 2021, 06:30",
    FriendlyStartDate: "6:30 AM",
    FriendlyEndDate: "7:15 AM",
    SeasonString: null,
    FriendlyLength: "45 minutes",
    FriendlyStartMonth: "November 1, 2021",
    FriendlyEndMonth: "December 27, 2021",
    FriendlyDaysOfWeek: "Mon",
    Amount: 4.0,
    NumRegistered: 0,
    MaxRegistrants: 29,
    BookmarkedDate: "0001-01-01T00:00:00",
    ExclusionDates: "",
    InclusionDates: "Nov 29,",
    Id: 1075554,
  },
  {
    ActivityId: 17901,
    FilterId: 0,
    ActivityTypeId: 22,
    ProgramId: 120,
    ProgramType: "Drop In Activities                      ",
    MinAge: 8.0,
    MaxAge: 99.0,
    MinAgeType: "Y",
    MaxAgeType: "Y",
    SubProgramType: "Swimming",
    Title: "Lane Swim &#8776",
    Description:
      "<span style='color:red;'><a href='http://www7.mississauga.ca/departments/rec/aquatics/docs/swim_admission_standards.pdf' target='_blank' style='color:red;'><strong>Note:</strong>Click here to view the swim admission standards to help you have a safe and positive swim experience.</a></span><br />  \r\nLane swim is a structured swim for continuous lap swimming. This swim is best for those whom are comfortable in deep water and can swim 25m. Pools are divided into double lanes to allow for a circular pattern while swimming. Lane division will be based on the pace of the swimmers.<p style='display:none;'>no-email-reminder</p>",
    Barcode: "906928",
    FacilityName: "Lap Pool",
    LocationId: 22,
    LocationName: "River Grove CC",
    LocationAddress: "5800 River Grove Mississauga ON L5M 4R9",
    NumberOfClasses: 7,
    StartDate: "2021-11-01T06:30:00",
    EndDate: "2021-12-13T07:15:00",
    FriendlyStartTime: "November 1, 2021, 6:30 AM",
    FriendlyStartTime_ForSorting: "November 1, 2021, 06:30",
    FriendlyStartDate: "6:30 AM",
    FriendlyEndDate: "7:15 AM",
    SeasonString: null,
    FriendlyLength: "45 minutes",
    FriendlyStartMonth: "November 1, 2021",
    FriendlyEndMonth: "December 13, 2021",
    FriendlyDaysOfWeek: "Mon",
    Amount: 4.0,
    NumRegistered: 0,
    MaxRegistrants: 29,
    BookmarkedDate: "0001-01-01T00:00:00",
    ExclusionDates: "",
    InclusionDates: "Nov 29,",
    Id: 1075753,
  },
  {
    ActivityId: 17901,
    FilterId: 0,
    ActivityTypeId: 22,
    ProgramId: 120,
    ProgramType: "Drop In Activities                      ",
    MinAge: 8.0,
    MaxAge: 99.0,
    MinAgeType: "Y",
    MaxAgeType: "Y",
    SubProgramType: "Swimming",
    Title: "Lane Swim &#8776",
    Description:
      "<span style='color:red;'><a href='http://www7.mississauga.ca/departments/rec/aquatics/docs/swim_admission_standards.pdf' target='_blank' style='color:red;'><strong>Note:</strong>Click here to view the swim admission standards to help you have a safe and positive swim experience.</a></span><br />  \r\nLane swim is a structured swim for continuous lap swimming. This swim is best for those whom are comfortable in deep water and can swim 25m. Pools are divided into double lanes to allow for a circular pattern while swimming. Lane division will be based on the pace of the swimmers.<p style='display:none;'>no-email-reminder</p>",
    Barcode: "907051",
    FacilityName: "Main Pool",
    LocationId: 5,
    LocationName: "Huron Park CC",
    LocationAddress: "830 Paisley Mississauga ON L5C 3P5",
    NumberOfClasses: 11,
    StartDate: "2021-10-29T06:30:00",
    EndDate: "2022-01-07T07:15:00",
    FriendlyStartTime: "October 29, 2021, 6:30 AM",
    FriendlyStartTime_ForSorting: "October 29, 2021, 06:30",
    FriendlyStartDate: "6:30 AM",
    FriendlyEndDate: "7:15 AM",
    SeasonString: null,
    FriendlyLength: "45 minutes",
    FriendlyStartMonth: "October 29, 2021",
    FriendlyEndMonth: "January 7, 2022",
    FriendlyDaysOfWeek: "Fri",
    Amount: 4.0,
    NumRegistered: 0,
    MaxRegistrants: 29,
    BookmarkedDate: "0001-01-01T00:00:00",
    ExclusionDates: "",
    InclusionDates: "Dec 03,",
    Id: 1075978,
  },
  {
    ActivityId: 17901,
    FilterId: 0,
    ActivityTypeId: 22,
    ProgramId: 120,
    ProgramType: "Drop In Activities                      ",
    MinAge: 8.0,
    MaxAge: 99.0,
    MinAgeType: "Y",
    MaxAgeType: "Y",
    SubProgramType: "Swimming",
    Title: "Lane Swim &#8776",
    Description:
      "<span style='color:red;'><a href='http://www7.mississauga.ca/departments/rec/aquatics/docs/swim_admission_standards.pdf' target='_blank' style='color:red;'><strong>Note:</strong>Click here to view the swim admission standards to help you have a safe and positive swim experience.</a></span><br />  \r\nLane swim is a structured swim for continuous lap swimming. This swim is best for those whom are comfortable in deep water and can swim 25m. Pools are divided into double lanes to allow for a circular pattern while swimming. Lane division will be based on the pace of the swimmers.<p style='display:none;'>no-email-reminder</p>",
    Barcode: "906694",
    FacilityName: "Main Pool",
    LocationId: 18,
    LocationName: "Malton CC and Library",
    LocationAddress: "3540 Morning Star Mississauga ON L4T 1Y2",
    NumberOfClasses: 28,
    StartDate: "2021-10-29T06:35:00",
    EndDate: "2021-12-31T07:20:00",
    FriendlyStartTime: "October 29, 2021, 6:35 AM",
    FriendlyStartTime_ForSorting: "October 29, 2021, 06:35",
    FriendlyStartDate: "6:35 AM",
    FriendlyEndDate: "7:20 AM",
    SeasonString: null,
    FriendlyLength: "45 minutes",
    FriendlyStartMonth: "October 29, 2021",
    FriendlyEndMonth: "December 31, 2021",
    FriendlyDaysOfWeek: "Mon, Wed, Fri",
    Amount: 4.0,
    NumRegistered: 0,
    MaxRegistrants: 16,
    BookmarkedDate: "0001-01-01T00:00:00",
    ExclusionDates: "",
    InclusionDates: "Nov 29,Dec 01,Dec 03,",
    Id: 1075518,
  },
  {
    ActivityId: 17896,
    FilterId: 0,
    ActivityTypeId: 22,
    ProgramId: 120,
    ProgramType: "Drop In Activities                      ",
    MinAge: 16.0,
    MaxAge: 99.0,
    MinAgeType: "Y",
    MaxAgeType: "Y",
    SubProgramType: "Swimming",
    Title: "Adult Leisure Swim &#8776",
    Description:
      "Adult leisure swim is an unstructured swim for those looking to exercise, socialize or relax in the water. This swim is open to persons 16 years of age and older.    <p style='display:none;'>no-email-reminder</p>",
    Barcode: "906717",
    FacilityName: "Therapeutic Pool",
    LocationId: 18,
    LocationName: "Malton CC and Library",
    LocationAddress: "3540 Morning Star Mississauga ON L4T 1Y2",
    NumberOfClasses: 28,
    StartDate: "2021-10-29T06:35:00",
    EndDate: "2021-12-31T07:20:00",
    FriendlyStartTime: "October 29, 2021, 6:35 AM",
    FriendlyStartTime_ForSorting: "October 29, 2021, 06:35",
    FriendlyStartDate: "6:35 AM",
    FriendlyEndDate: "7:20 AM",
    SeasonString: null,
    FriendlyLength: "45 minutes",
    FriendlyStartMonth: "October 29, 2021",
    FriendlyEndMonth: "December 31, 2021",
    FriendlyDaysOfWeek: "Mon, Wed, Fri",
    Amount: 4.0,
    NumRegistered: 0,
    MaxRegistrants: 20,
    BookmarkedDate: "0001-01-01T00:00:00",
    ExclusionDates: "",
    InclusionDates: "Nov 29,Dec 01,Dec 03,",
    Id: 1075541,
  },
];

export default function Schedule() {
  return (
    <div className="bg-white overflow-hidden">
      <div role="list" className="">
        {activities.map((activity) => (
          <ActivityCard activity={activity}></ActivityCard>
        ))}
      </div>
    </div>
  );
}
